### ISSUE TITLE
无法添加新的订阅

### ISSUE THREAD

**Issue by endlessland** [Colter23/bilibili-dynamic-mirai-plugin#101]
版本：[v3.2.6](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.2.6)
qq中输入：/bili add xxx（输入的uid）
终端：
2023-04-21 12:08:06 W/BiliBili Dynamic: Exception in executing command `[mirai:source:ids=[62640], internalIds=[158835085], from group qq号 to 群号 at 1682050085]/bili add 输入的uid`
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 47: Expected EOF after parsing, but had { instead at path: $
JSON input: .....sage":"请求过于频繁，请稍后再试","ttl":1}{"code":0,"message":"0","ttl":1.....
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:528)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:526)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.expectEof(AbstractJsonLexer.kt:166)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:101)
        at kotlinx.serialization.json.Json.parseToJsonElement(Json.kt:128)
        at bilibili-dynamic-mirai-plugin-3.2.6.mirai2.jar//top.colter.mirai.plugin.bilibili.api.UserKt.userInfo(User.kt:158)
        at bilibili-dynamic-mirai-plugin-3.2.6.mirai2.jar//top.colter.mirai.plugin.bilibili.api.UserKt$userInfo$1.invokeSuspend(User.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
  
>

**Comment by Colter23** [comment]
b站跟新了api。等待更新

**Comment by Colter23** [comment]
已修复 https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.2.8
