### ISSUE TITLE
使用add订阅，提示访问权限不足

### ISSUE THREAD

**Issue by WeiLanKing** [Colter23/bilibili-dynamic-mirai-plugin#103]
java.lang.Exception: URL: https://api.bilibili.com/x/space/wbi/acc/info, CODE: -403, MSG: 访问权限不足
        at bilibili-dynamic-mirai-plugin-3.2.8.mirai2.jar//top.colter.mirai.plugin.bilibili.api.UserKt.userInfo(User.kt:223)
        at bilibili-dynamic-mirai-plugin-3.2.8.mirai2.jar//top.colter.mirai.plugin.bilibili.api.UserKt$userInfo$1.invokeSuspend(User.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by Naka152** [comment]
同问题

**Comment by wyc-java-01** [comment]
同报错，B站关注了，但是并没有订阅成功
java.lang.Exception: URL: https://api.bilibili.com/x/space/wbi/acc/info, CODE: -403, MSG: 访问权限不足
	at bilibili-dynamic-mirai-plugin-3.2.8.mirai2.jar//top.colter.mirai.plugin.bilibili.api.UserKt.userInfo(User.kt:223)
	at bilibili-dynamic-mirai-plugin-3.2.8.mirai2.jar//top.colter.mirai.plugin.bilibili.api.UserKt$userInfo$1.invokeSuspend(User.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by Colter23** [comment]
https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.2.9 修了
