### ISSUE TITLE
[Bug] 订阅用户时出错

### ISSUE THREAD

**Issue by XieXiLin2** [Colter23/bilibili-dynamic-mirai-plugin#104]
执行  `.bili add 634651362` 时有以下报错:

``` 
2023-06-06 00:37:39 W/BiliBili Dynamic: Exception in executing command `[mirai:source:ids=[232766], internalIds=[857747709], from group 3068342155 to 768176998 at 1685983059].bili add 634651362`                                                                                              java.lang.Exception: URL: https://api.bilibili.com/x/space/wbi/acc/info, CODE: -403, MSG: 访问权限不足                                                                                                  at bilibili-dynamic-mirai-plugin-3.2.8.mirai2.jar//top.colter.mirai.plugin.bilibili.api.UserKt.userInfo(User.kt:223)                                                                            at bilibili-dynamic-mirai-plugin-3.2.8.mirai2.jar//top.colter.mirai.plugin.bilibili.api.UserKt$userInfo$1.invokeSuspend(User.kt)                                                                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                                                                                       at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)                         at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)                    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)                                                                                                       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)                                 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)                                                                                               at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)                                                                                                 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
``` 

已登录、确认账号没问题。
(为什么这日志自动压缩到一行了……)

**Comment by Colter23** [comment]
更新

**Comment by XieXiLin2** [comment]
现在可以了，麻烦您了。
