### ISSUE TITLE
填写cookie后报错

### ISSUE THREAD

**Issue by hhhfsj** [Colter23/bilibili-dynamic-mirai-plugin#18]
`2021-11-22 08:35:56 E/BilibiliDynamic: kotlin.NotImplementedError: An operation
is not implemented: MULTILINE STRING
kotlin.NotImplementedError: An operation is not implemented: MULTILINE STRING
        at net.mamoe.yamlkt.internal.YamlUtils__EscapeKt.readUnquotedString(Esca
pe.kt:175)
        at net.mamoe.yamlkt.internal.YamlUtils.readUnquotedString(Unknown Source
)
        at net.mamoe.yamlkt.internal.TokenStream.prepareStringAndNextToken(Token
Stream.kt:308)
        at net.mamoe.yamlkt.internal.TokenStream.nextToken(TokenStream.kt:282)
        at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.nextToken(YamlD
ecoder.kt:98)
        at net.mamoe.yamlkt.internal.YamlDecoder$BlockClassDecoder.decodeElement
Index(YamlDecoder.kt:280)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerialize
r$1.deserialize(PluginDataImpl.kt:75)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerialize
r$1.deserialize(PluginDataImpl.kt:47)
        at net.mamoe.yamlkt.Yaml.decodeFromString(Yaml.kt:162)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.
load(MultiFilePluginDataStorageImpl.kt:39)
        at net.mamoe.mirai.console.plugin.jvm.AbstractJvmPlugin.reloadPluginConf
ig(AbstractJvmPlugin.kt:58)
        at top.colter.mirai.plugin.bilibili.PluginMain.onEnable(PluginMain.kt:39
)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnE
nable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.en
able(BuiltInJvmPluginLoaderImpl.kt:122)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(Jvm
PluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(Jvm
PluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManag
er.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLo
adedPlugins$mirai_console(PluginManagerImpl.kt:172)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doS
tart$mirai_console(MiraiConsoleImplementationBridge.kt:208)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(Mi
raiConsoleImplementation.kt:276)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa
emon(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa
emon$default(MiraiConsoleTerminalLoader.kt:151)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(Mira
iConsoleTerminalLoader.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow
n Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un
known Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow
n Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un
known Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:22
6)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:169
2)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j
ava:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:4
12)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:357
8)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j
ava:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.j
ava:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdap
ter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:
105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.j
ava:126)
        at jdk.proxy1/jdk.proxy1.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106
)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)`

**Comment by Colter23** [comment]
请确保你的cookie为一行，中间不要有换行，且包含在双引号内

**Comment by hhhfsj** [comment]
找到原因了，配置文件生成的是单引号，改成双引就好了

**Comment by CCYellowStar** [comment]
我试试

**Comment by CCYellowStar** [comment]
解决了
