### ISSUE TITLE
无法从当前环境获取联系人

### ISSUE THREAD

**Issue by GuuGuai** [Colter23/bilibili-dynamic-mirai-plugin#37]
执行bili add之后报错如下

2022-01-18 12:04:38 E/console: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow
n Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un
known Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(Caller
Impl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(Calle
rImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_re
flection(KCallableImpl.kt:173)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:73)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubComm
ands$6$1.invokeSuspend(CommandReflector.kt:305)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubComm
ands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubComm
ands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunct
ionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunct
ionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.execute
CommandImpl(CommandManagerImpl.kt:163)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(Command
Manager.kt:130)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeComman
d(CommandManager.kt)
        at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread
$3.invokeSuspend(ConsoleThread.kt:191)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
Scheduler.kt:665)
Caused by: net.mamoe.mirai.console.command.descriptor.CommandArgumentParserExcep
tion: 无法从当前环境获取联系人
        at top.colter.mirai.plugin.bilibili.command.DynamicCommandKt.Contact(Dyn
amicCommand.kt:68)
        at top.colter.mirai.plugin.bilibili.command.DynamicCommand.add$default(D
ynamicCommand.kt:45)
        ... 23 more

**Comment by Initial-heart-1** [comment]
确保在聊天环境执行命令而不是 console
或，请在 UID 后加一个空格写上目标群号
另外，你的 issues 缺少关键信息以至于我无法正确定位问题，以上是常见的解决方案

**Comment by Initial-heart-1** [comment]
若问题解决且无其他问题，请 close issue
