### ISSUE TITLE
本插件的2.1.2和2.1.3版本，会与MiraiNative插件的图形化界面功能出现冲突

### ISSUE THREAD

**Issue by byx2020** [Colter23/bilibili-dynamic-mirai-plugin#42]
这是一个令人困惑的问题，我在将本插件更新到了2.1.2和2.1.3版本之后，发现[MiraiNative插件](https://github.com/iTXTech/mirai-native)本应该出现在右下角任务栏的图标没有正常显示(会导致MiraiNative里面所有插件的图形化设置界面无法打开，只能通过配置文件更改设置项)，不过MiraiNative插件之前已经设置好了的功能是可以正常运行的(暂未发现其他问题)。
经过一番排查后，确定了当本插件的2.1.2或2.1.3版本与MiraiNative插件同时运行就会出现MiraiNative插件的任务栏图标无法正常显示的问题(此插件的2.1.1及以下版本，实测不会出现这种情况)。

以下为插件运行环境信息：
服务器配置：2C4G
操作系统：Windows Server 2012 R2 DataCenter 64bitCN
JRE版本：OpenJDK Runtime Environment Temurin-11.0.12+7 (11.0.12+7) (build 11.0.12+7)
Java VM：OpenJDK Client VM Temurin-11.0.12+7 (11.0.12+7, mixed mode, serial gc, windows-x86)
Mirai版本：2.10.0(最新版)
插件版本：2.1.1、2.1.2、2.1.3
其他说明：当安装了本插件的2.1.2或2.1.3版本后，会导致MiraiNative插件出现以下报错信息(实测本插件的2.1.1版本不会导致此报错)。
```
2022-02-06 13:41:18 V/JvmPluginLoader: Enabling plugin MiraiNative v2.0.0-beta.1

2022-02-06 13:41:18 E/MiraiNative: java.awt.HeadlessException
java.awt.HeadlessException
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(Unknown Sourc
e)
        at java.desktop/java.awt.Window.<init>(Unknown Source)
        at java.desktop/java.awt.Frame.<init>(Unknown Source)
        at java.desktop/javax.swing.JFrame.<init>(Unknown Source)
        at org.itxtech.mirainative.ui.FloatingWindow.create(FloatingWindow.kt:50
)
        at org.itxtech.mirainative.MiraiNative.onEnable(MiraiNative.kt:160)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnE
nable$mirai_console(JvmPluginInternal.kt:117)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.en
able(BuiltInJvmPluginLoaderImpl.kt:164)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.en
able(BuiltInJvmPluginLoaderImpl.kt:36)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(Jvm
PluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(Jvm
PluginLoader.kt:47)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManag
er.kt:135)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLo
adedPlugins$mirai_console(PluginManagerImpl.kt:177)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doS
tart$mirai_console(MiraiConsoleImplementationBridge.kt:202)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(Mi
raiConsoleImplementation.kt:392)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa
emon(MiraiConsoleTerminalLoader.kt:156)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa
emon$default(MiraiConsoleTerminalLoader.kt:155)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(Mira
iConsoleTerminalLoader.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow
n Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un
known Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow
n Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un
known Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:22
6)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:169
2)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j
ava:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:4
12)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:357
8)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j
ava:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.j
ava:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdap
ter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:
105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.j
ava:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106
)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)

2022-02-06 13:41:18 I/MiraiNative: 正在加载 Mirai Native Bridge C:\Software\Mira
i-0\data\org.itxtech.mirainative\CQP.dll
```

**Comment by Initial-heart-1** [comment]
标题写太长了吧
报的 java.awt.HeadlessException，我无法理解！发生甚么事了抛个这
@Colter23 你加油，我润了

**Comment by Colter23** [comment]
估计是因为我加了这一句 `System.setProperty("java.awt.headless", "true")` 。emmm       

还有如果你不知道的话就别凑热闹了 @Initial-heart-1

**Comment by byx2020** [comment]
> 估计是因为我加了这一句 `System.setProperty("java.awt.headless", "true")` 。emmm，晚上修

@Colter23 好的，麻烦大佬了，如果万一还需要其他问题相关信息或日志，也可以让我提供。

**Comment by Colter23** [comment]
@byx2020 [v2.1.4](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v2.1.4)  （感觉我在刷releases，两天3个版本。。

**Comment by byx2020** [comment]
> @byx2020 [v2.1.4](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v2.1.4) （感觉我在刷releases，两天3个版本。。

@Colter23 测试结果：在2.1.4版本，此问题不再出现，感谢大佬的更新。

**Comment by Initial-heart-1** [comment]
> 估计是因为我加了这一句 `System.setProperty("java.awt.headless", "true")` 。emmm，晚上修
> 
> 还有如果你不知道的话就别凑热闹了 @Initial-heart-1

主要我回去翻提交记录人直接傻了，然后开摆

**Comment by Initial-heart-1** [comment]
> 主要我回去翻提交记录人直接傻了，然后开摆

一片绿，我滚轮一下就划过去了，刚好没看着
离谱，痛失 PR
