### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit

### ISSUE THREAD

**Issue by YuanNing-96** [Colter23/bilibili-dynamic-mirai-plugin#56]
在文字推送模式下检测到新动态（我用另一个账号转发了一条视频）的时候会提示这个错误：
2022-04-14 23:07:45 E/BilibiliDynamic: ERROR java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit

在使用/bili login命令登陆的时候会提示这个错误：
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:305)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
	at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:167)
	at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:131)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:126)
	at net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:86)
	at net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:69)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.UnsatisfiedLinkError: /root/java/lib/libawt_xawt.so: libXrender.so.1: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at java.desktop/java.awt.image.ColorModel$1.run(Unknown Source)
	at java.desktop/java.awt.image.ColorModel$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.image.ColorModel.loadLibraries(Unknown Source)
	at java.desktop/java.awt.image.ColorModel.<clinit>(Unknown Source)
	at java.desktop/java.awt.image.BufferedImage.<clinit>(Unknown Source)
	at com.google.zxing.client.j2se.MatrixToImageWriter.toBufferedImage(MatrixToImageWriter.java:63)
	at com.google.zxing.client.j2se.MatrixToImageWriter.writeToPath(MatrixToImageWriter.java:128)
	at com.google.zxing.client.j2se.MatrixToImageWriter.writeToPath(MatrixToImageWriter.java:100)
	at top.colter.mirai.plugin.bilibili.DynamicTasker.login(BiliBiliTasker.kt:296)
	at top.colter.mirai.plugin.bilibili.command.DynamicCommand.login(DynamicCommand.kt:107)
	... 26 more

在图片模式推送下检测到新动态（我用另一个账号转发了一条视频）时，会报这个错误：
2022-04-14 23:09:23 E/BilibiliDynamic: ERROR java.lang.NoClassDefFoundError: Could not initialize class 
 top.colter.mirai.plugin.bilibili.utils.ImgUtils

运行在阿里云的2核2GiB内存1Mbps带宽的Ubuntu 20.04 64位服务器上
只手动安装了这个插件以及依赖的那个插件。
使用的java版本是https://github.com/iTXTech/mcl-installer/releases这个里安装的jre，版本号17并且是64位。

不知道是我配置出了什么问题还是怎么地了，2333

**Comment by YuanNing-96** [comment]
忘记写了，使用的版本是release里的v2.2.1的jar

**Comment by Colter23** [comment]
环境问题，启动时加上这串参数  `-Djava.awt.headless=true`

**Comment by YuanNing-96** [comment]
上网查了半天，终于找到了在哪里加参数。
手动修改mcl文件，在-jar参数前面加这个参数，不要在./mcl文件的后面加这个参数

示例：（仅关注第三行的修改部分就可以，第二行的参数因为java的位置而不同）
#!/usr/bin/env sh
export JAVA_BINARY="/root/java/bin/java"
$JAVA_BINARY -Djava.awt.headless=true -jar mcl.jar $*

感谢Colter23大佬的指点
