### ISSUE TITLE
无法解析的链接

### ISSUE THREAD

**Issue by GT-TieGuan** [Colter23/bilibili-dynamic-mirai-plugin#81]
https://www.bilibili.com/video/BV13G411M7G4
账号已经打码。
```
2022-12-09 14:30:03 I/BiliBili Dynamic: 开始解析链接 -> https://www.bilibili.com/video/BV13G411M7G4
2022-12-09 14:30:03 W/Bot.2*********: An exception occurred when processing event. Subscriber scope: 'ListenerTasker'. Broadcaster scope: 'Bot 2*********.EventDispatcher'
kotlinx.serialization.json.internal.JsonDecodingException: Expected JsonPrimitive at premiere, found {"state":3,"start_time":1670491800,"now_time":1670567415,"room_id":741302,"sid":0}
JSON input: .....b":{"url_image_ani_cut":""},"honor_reply":{},"like_icon":""}
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.getPrimitiveValue(TreeJsonDecoder.kt:77)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedString(TreeJsonDecoder.kt:149)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedString(TreeJsonDecoder.kt:35)
        at kotlinx.serialization.internal.TaggedDecoder.decodeString(Tagged.kt:231)
        at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:142)
        at kotlinx.serialization.internal.StringSerializer.deserialize(Primitives.kt:138)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
        at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:288)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:287)
        at bilibili-dynamic-mirai-plugin-3.2.0.jar//top.colter.mirai.plugin.bilibili.data.VideoDetail$$serializer.deserialize(Video.kt:6)
        at bilibili-dynamic-mirai-plugin-3.2.0.jar//top.colter.mirai.plugin.bilibili.data.VideoDetail$$serializer.deserialize(Video.kt:6)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.NullableSerializer.deserialize(NullableSerializer.kt:30)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
        at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
        at bilibili-dynamic-mirai-plugin-3.2.0.jar//top.colter.mirai.plugin.bilibili.api.DynamicKt.getVideoDetail(Dynamic.kt:152)
        at bilibili-dynamic-mirai-plugin-3.2.0.jar//top.colter.mirai.plugin.bilibili.api.DynamicKt$getVideoDetail$1.invokeSuspend(Dynamic.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Colter23** [comment]
https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.2.2
