### ISSUE TITLE
获取最新动态时用户没有动态报错

### ISSUE THREAD

**Issue by MuBai-He** [Colter23/bilibili-dynamic-mirai-plugin#82]
``/bili new 22637261 1
2022-12-13 13:45:49 W/BiliBili Dynamic: Exception in executing command `[mirai:source:ids=[6914], internalIds=[1366796072], from group 2586595521 to 736419964 at 1670910348]/bili new 22637261 1`
java.lang.IndexOutOfBoundsException: toIndex = 1
        at java.base/java.util.AbstractList.subListRangeCheck(Unknown Source)
        at java.base/java.util.ArrayList.subList(Unknown Source)
        at bilibili-dynamic-mirai-plugin-3.2.1.mirai2.jar//top.colter.mirai.plugin.bilibili.command.DynamicCommand.new(DynamicCommand.kt:274)
        at bilibili-dynamic-mirai-plugin-3.2.1.mirai2.jar//top.colter.mirai.plugin.bilibili.command.DynamicCommand$new$1.invokeSuspend(DynamicCommand.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)``

**Comment by Colter23** [comment]
因为这  [22637261](https://space.bilibili.com/22637261/dynamic) 本来就没动态。。不过没动态报错且没有提示消息确实是个bug

**Comment by MuBai-He** [comment]
谢谢
